/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.expertoweb.Batch_IJ;

import ij.plugin.frame.PlugInFrame;;  
import ij.gui.GenericDialog;  
import ij.ImagePlus;  
import ij.process.*;  
import ij.IJ;  
import ij.Macro;  
import java.awt.Color; 

/**
 *
 * @author expertoweb
 */
public class Batch_IJ extends PlugInFrame {

    /**
     * Creates new form Batch_IJ_Frame
     */
    public Batch_IJ() {
        super("FrameDemo");
        initComponents();
    }
    
    public void run(String arg) {  
  
        // A - Without automation: the dialog shows  
        ImagePlus imp = createImage();  
        if (null != imp) imp.show();  
  
        // B - With automation: the dialog never shows:  
  
        Thread thread = Thread.currentThread();  
        thread.setName("Run$_create_image");  
  
        // ... so we can create many images in a loop, for example.  
        for (int i=1; i<=3; i++) {  
            // Create a 1024x1024 image, 160bit, with noise added  
            // and with the title storing the loop index:  
            Macro.setOptions(thread, "title='My new image " + i + "'"  
                  + " width=1024 height=1024 type='16-bit' add_noise");  
            // Above, notice how we do not set the fill_value key,  
            //     so that its default value (zero in this case) is taken.  
            ImagePlus imp2 = createImage();  
            imp2.show();  
        }  
  
        // Cleanup: remove reference to the Thread and its associated options  
        Macro.setOptions(thread, null);  
        
        this.show();
    }  
  
    public ImagePlus createImage() {  
        final GenericDialog gd = new GenericDialog("Create image");  
        gd.addStringField("title:", "new");  
        gd.addNumericField("width:", 512, 0);  
        gd.addNumericField("height:", 512, 0);  
        final String[] types = new String[]{"8-bit", "16-bit", "32-bit", "RGB"};  
        gd.addChoice("type:", types, types[0]);  
        gd.addSlider("fill_value:", 0, 255, 0); // min, max, default  
        gd.addCheckbox("add_noise", false);  
        gd.showDialog();  
        if (gd.wasCanceled()) return null;  
  
        final String title = gd.getNextString();  
        final int width = (int)gd.getNextNumber();  
        final int height = (int)gd.getNextNumber();  
        final int itype = gd.getNextChoiceIndex();  
        final double fill_value = gd.getNextNumber();  
        final boolean add_noise = gd.getNextBoolean();  
  
        ImageProcessor ip = null;  
  
        switch (itype) {  
            case 0: ip = new ByteProcessor(width, height);  break;  
            case 1: ip = new ShortProcessor(width, height); break;  
            case 2: ip = new FloatProcessor(width, height); break;  
            case 3: ip = new ColorProcessor(width, height); break;  
        }  
  
        // Color images are created filled with white by default  
        if (3 == itype && 255 != fill_value) {  
            // color image  
            ip.setColor(new Color((int)fill_value, (int)fill_value, (int)fill_value));  
            ip.fill();  
        }  
        // non-color images  
        else if (0 != fill_value) {  
            ip.setValue(fill_value);  
            ip.fill();  
        }  
  
        final ImagePlus imp = new ImagePlus(title, ip);  
  
        if (add_noise) IJ.run(imp, "Add Noise", "");  
  
        return imp;  
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        checkbox1 = new java.awt.Checkbox();
        button1 = new java.awt.Button();
        panel1 = new java.awt.Panel();
        jPanel5 = new javax.swing.JPanel();
        panel2 = new java.awt.Panel();
        checkbox2 = new java.awt.Checkbox();
        checkbox3 = new java.awt.Checkbox();
        button2 = new java.awt.Button();
        panel3 = new java.awt.Panel();

        jRadioButton1.setText("jRadioButton1");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        checkbox1.setLabel("checkbox1");
        jPanel4.add(checkbox1);

        button1.setLabel("button1");
        jPanel4.add(button1);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        panel2.setBackground(new java.awt.Color(204, 204, 204));
        panel2.setLayout(new java.awt.GridLayout(8, 1));

        checkbox2.setLabel("checkbox2");
        panel2.add(checkbox2);

        checkbox3.setLabel("checkbox3");
        panel2.add(checkbox3);

        button2.setLabel("button2");
        panel2.add(button2);

        add(panel2, java.awt.BorderLayout.WEST);

        panel3.setBackground(new java.awt.Color(153, 153, 153));
        add(panel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Batch_IJ().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    private java.awt.Checkbox checkbox3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
